qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_1.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_2.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_3.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_4.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_5.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_6.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_7.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_8.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_9.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_10.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_11.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_12.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_13.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_14.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_15.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_16.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_17.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_18.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_19.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_20.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_21.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_22.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_23.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_24.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_25.sh
wait
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-test-SVR/combined_jobs/EXP-final-test-SVR_26.sh
