qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_1.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_2.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_3.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_4.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_5.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_6.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_7.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_8.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_9.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_10.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_11.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_12.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_13.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_14.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_15.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_16.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_17.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_18.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_19.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_20.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_21.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_22.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_23.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_24.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_25.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_26.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_27.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_28.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_29.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_30.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_31.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_32.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_33.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_34.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_35.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_36.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_37.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_38.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_39.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_40.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_41.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_42.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_43.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_44.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_45.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_46.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_47.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_48.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_49.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_50.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/combined_jobs/EXP-final-GB_51.sh
