qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_1.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_2.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_3.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_4.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_5.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_6.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_7.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_8.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_9.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_10.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_11.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB/seperate_jobs/EXP-final-GB_12.sh
