qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_1.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_2.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_3.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_4.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_5.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_6.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_7.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_8.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_9.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_10.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_11.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_12.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_13.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_14.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_15.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_16.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_17.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_18.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_19.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_20.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_21.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_22.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_23.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_24.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_25.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_26.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_27.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_28.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_29.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_30.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_31.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_32.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_33.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_34.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_35.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_36.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_37.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_38.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_39.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_40.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_41.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_42.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_43.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_44.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_45.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_46.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_47.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_48.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_49.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_50.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/combined_jobs/EXP-final-SVR-normal-shap_51.sh
