qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_1.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_2.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_3.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_4.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_5.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_6.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_7.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_8.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_9.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_10.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_11.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-SVR-normal-shap/seperate_jobs/EXP-final-SVR-normal-shap_12.sh
