qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_1.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_2.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_3.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_4.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_5.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_6.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_7.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_8.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_9.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_10.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_11.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_12.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_13.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_14.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_15.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_16.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_17.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_18.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_19.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_20.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_21.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_22.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_23.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_24.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_25.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-RF/combined_jobs/EXP-final-RF_26.sh
