qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_1.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_2.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_3.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_4.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_5.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_6.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_7.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_8.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_9.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_10.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_11.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_12.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_13.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_14.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_15.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_16.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_17.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_18.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_19.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_20.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_21.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_22.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_23.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_24.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_25.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_26.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_27.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_28.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_29.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_30.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_31.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_32.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_33.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_34.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_35.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_36.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_37.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_38.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_39.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_40.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_41.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_42.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_43.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_44.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_45.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_46.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_47.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_48.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_49.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_50.sh
qsub /projectnb/skiran/saurav/Fall-2022/src2/experiment_jobs/EXP-final-GB-normal/combined_jobs/EXP-final-GB-normal_51.sh
